[tools]
watchexec = "latest"
node = "latest"
"npm:purs-tidy" = "latest"
"npm:bun" = "canary"
"npm:spago" = "next"
"npm:@biomejs/biome" = "latest"
"npm:rimraf" = "latest"
"npm:purescript" = "next"

[settings]
experimental = true

[hooks]
postinstall = [
  "bun install",
  "spago install",
]

[tasks.dev]
wait_for = ["make"]
depends = ["make", "dev-bun", "dev-spago"]

[tasks.dev-bun]
run = "watchexec -w src -e ts -- bun build-bun.ts"

[tasks.dev-spago]
run = "watchexec -w src -e js,purs -- spago build"

[tasks.format]
run = [
  "purs-tidy format-in-place 'src/**/*.purs' 'test/**/*.purs'",
  "biome format --write .",
]

[tasks.make]
run = [
  "bun build-bun.ts",
  "spago build",
]

[tasks.build]
depends = ["make"]

[tasks.test]
depends = ["make"]
run = [
  "spago test",
  "bun output/Test.Main/index.js"
]

[tasks.clean]
run = "rimraf output node_modules .spago bun.lock .build-cache"
