[tools]
node = "latest"
"npm:purs-tidy" = "latest"
"npm:bun" = "canary"
"npm:spago" = "next"
"npm:@biomejs/biome" = "latest"
"npm:rimraf" = "latest"
"npm:purescript" = "next"

[tasks.format]
run = [
  "purs-tidy format-in-place 'src/**/*.purs' 'test/**/*.purs'",
  "biome format --write .",
]

[tasks.build]
depends = ["make"]

[tasks.make]
depends = ["install"]
run = "spago build"

[tasks.install]
run = [
  "bun install",
  "spago install",
]

[tasks.test]
depends = ["make"]
run = [
  "spago test",
  "bun output/Test.Main/index.js"
]

[tasks.clean]
run = "rimraf output node_modules .spago"
