#!/usr/bin/env python3
"""Generate deterministic Dew WASI marshalling cases."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TARGET = ROOT / "tools/wasi-parity/generated_cases.dew"
BOUNDARY_LENGTHS = [
    0,
    1,
    15,
    16,
    17,
    4095,
    4096,
    4097,
    8192,
    8193,
    10000,
    65519,
    65520,
    65521,
    100000,
]
ALIGNMENT_LENGTH = 5003


def dew_bytes(data: bytes) -> str:
    pieces: list[str] = []
    for byte in data:
        if byte == 0x22:
            pieces.append('\\"')
        elif byte == 0x5C:
            pieces.append("\\\\")
        elif 0x20 <= byte <= 0x7E:
            pieces.append(chr(byte))
        else:
            pieces.append(f"\\x{byte:02X}")
    return 'b"' + "".join(pieces) + '"'


def payload(length: int, salt: int) -> bytes:
    return bytes(((index * 131 + salt * 17 + 7) & 0xFF) for index in range(length))


def write_case(name: str, length: int, alignment: int, salt: int) -> str:
    logical = payload(length, salt)
    backing = bytes([0xA0 + alignment]) * alignment + logical + b"TAIL"
    return (
        f"pub fn {name}(fd: U32) -> U32 {{\n"
        f"  wasi_fd_write(fd, {dew_bytes(backing)}.view({alignment}u32, {length}u32))\n"
        f"}}\n"
    )


def main() -> None:
    output = [
        "// Generated by tools/wasi-parity/generate_cases.py.\n",
        "open dew.std.bytes\n",
        "open dew.std.wasi\n",
        "\n",
        "builtin bench_wasi_stage_write(value: Bytes) -> U32 = \"dew_bench_wasi_stage_write\"\n",
        "builtin bench_wasi_stage_read(length: U32) -> Bytes = \"dew_bench_wasi_stage_read\"\n",
    ]
    for length in BOUNDARY_LENGTHS:
        alignment = (length * 7) % 16
        output.append(write_case(f"write_boundary_{length}", length, alignment, length + 1))
        output.append(
            f"pub fn copy_boundary_{length}(input_fd: U32, output_fd: U32) -> U32 {{\n"
            f"  wasi_fd_write(output_fd, wasi_fd_read(input_fd, {length}u32))\n"
            f"}}\n"
        )
    for alignment in range(16):
        output.append(
            write_case(
                f"write_alignment_{alignment}",
                ALIGNMENT_LENGTH,
                alignment,
                1000 + alignment,
            )
        )
    output.append(
        "pub fn copy_dynamic(input_fd: U32, output_fd: U32, limit: U32) -> U32 {\n"
        "  wasi_fd_write(output_fd, wasi_fd_read(input_fd, limit))\n"
        "}\n"
    )
    for length in [4096, 10000, 65520, 100000]:
        output.append(
            f"pub fn read_length_{length}(fd: U32) -> U32 {{\n"
            f"  wasi_fd_read(fd, {length}u32).byte_length()\n"
            f"}}\n"
        )
    for length in [4096, 10000, 65520]:
        alignment = (length * 7) % 16
        logical = payload(length, length + 1)
        backing = bytes([0xA0 + alignment]) * alignment + logical + b"TAIL"
        output.append(
            f"pub fn stage_write_{length}() -> U32 {{\n"
            f"  bench_wasi_stage_write({dew_bytes(backing)}.view({alignment}u32, {length}u32))\n"
            f"}}\n"
        )
        output.append(
            f"pub fn stage_read_{length}() -> U32 {{\n"
            f"  bench_wasi_stage_read({length}u32).byte_length()\n"
            f"}}\n"
        )
    output.append(
        "pub fn host_write_call(fd: U32) -> U32 {\n"
        "  wasi_fd_write_import(fd, 0u32, 1u32, 8u32)\n"
        "}\n"
    )
    output.append(
        "pub fn host_read_call(fd: U32) -> U32 {\n"
        "  wasi_fd_read_import(fd, 0u32, 1u32, 8u32)\n"
        "}\n"
    )
    output.append(
        "pub fn write_probe(fd: U32) -> U32 {\n"
        "  wasi_fd_write(fd, b\"probe-data\")\n"
        "}\n"
    )
    output.append(
        "pub fn read_probe(fd: U32) -> U32 {\n"
        "  wasi_fd_read(fd, 64u32).byte_length()\n"
        "}\n"
    )
    TARGET.write_text("\n".join(output), encoding="utf-8")
    print(f"generated {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
