module Dewdrop.Passes.TypeIRLower where

import Prelude

import Data.Dewdrop.AST (Expr, ExprKind(..), FnParam, Module, ModuleDeclaration, ModuleDeclarationKind(..), ModuleFn, TypeExpr, TypeExprKind, WhenArm)
import Data.Dewdrop.Compiler (Compiler(..), ModuleContext(..))
import Data.Dewdrop.IR (IRContext, TypedIRID)
import Data.Dewdrop.Identifier (Identifier)
import Data.Dewdrop.Types (ProgramType, builtin_integer_type)
import Data.Dewdrop.Visitor (class Pass, class Visitable, continue, exit, ignore, skip_all, visit)
import Data.List (List(..), (:))
import Data.Map (Map)
import Data.Map as Map
import Data.Maybe (Maybe(..))
import Data.Tuple (Tuple(..))
import Dewdrop.IR (ir_fn_context_new, ir_int_const)
import Record (merge)

newtype LowerIRContextProps = LowerIRContextProps { module_ctx :: ModuleContext }

type IREnv = Map Identifier TypedIRID
newtype LowerIRContext system_ctx = LowerIRContext
  -- storage for the compiler state
  { compiler :: Compiler system_ctx

  -- Scope Stack and Function Stack
  , env_stack :: List IREnv
  , fn_stack :: List IRContext

  -- IR Stack
  -- The IR Stack contains pointers to each generated IR binding
  , ir_stack :: List TypedIRID
  , module_ctx :: ModuleContext

  -- Type Stack
  -- Each Type expression manipulates the top of the type stack, eventually popping the stack to
  -- obtain a resolved value.
  , type_stack :: List ProgramType
  }

ctx_new :: ∀ (@system_ctx :: Type). Compiler system_ctx -> ModuleContext -> LowerIRContext system_ctx
ctx_new compiler module_ctx = LowerIRContext { compiler, env_stack: Nil, ir_stack: Nil, module_ctx, fn_stack: Nil, type_stack: Nil }

run :: ∀ (@u :: Type). Pass Module (LowerIRContext u) => Visitable Module (LowerIRContext u) => LowerIRContextProps -> Compiler u -> Maybe (Compiler u)
run (LowerIRContextProps { module_ctx }) compiler = do
  let
    (ModuleContext { ast, id }) = module_ctx
    ctx = ctx_new compiler module_ctx
  Tuple (LowerIRContext { compiler: (Compiler inner_compiler'), module_ctx: (ModuleContext inner_module_ctx') }) ast' <- visit ast ctx
  let
    module_ctx' = ModuleContext $ merge { ast: ast' } inner_module_ctx'
    compiler' = Compiler $ merge { modules: Map.insert id module_ctx' inner_compiler'.modules } inner_compiler'
  pure compiler'

instance type_ir_lower_module_pass :: Pass Module (LowerIRContext u) where
  enter = ignore
  exit = ignore

instance type_ir_lower_declaration_pass :: Pass ModuleDeclaration (LowerIRContext u) where
  enter = ignore
  exit = ignore

-- Visitable over ctx => over -> ctx -> VisitResult ctx over
instance type_ir_lower_declaration_kind_pass :: Pass ModuleDeclarationKind (LowerIRContext u) where
  enter = ignore

  -- When we exit a function declaration, we need to associate the name of the function with it's simplified IR Context
  exit (FnDeclarationKind _ name _) (LowerIRContext inner_ctx@{ compiler, module_ctx, fn_stack: (fn_context : fn_stack) }) = do
    let
      ModuleContext inner_module_ctx@{ id, fns } = module_ctx
      Compiler inner_compiler@{ modules } = compiler

      -- The fn_context on top of the stack was generated by the inner visitor, and needs to be popped
      fns' = Map.insert name fn_context fns

      module_ctx' = ModuleContext $ merge { fns: fns' } inner_module_ctx
      compiler' = Compiler $ merge { modules: Map.insert id module_ctx' modules } inner_compiler
      ctx' = LowerIRContext $ merge { module_ctx: module_ctx', compiler: compiler', fn_stack } inner_ctx
    continue ctx'

  -- In the case where no pattern is matched, it's an error
  exit _ _ = Nothing

instance type_ir_lower_fn_pass :: Pass ModuleFn (LowerIRContext u) where
  -- for each module function, something is processing it. Create a fn context
  -- push it to the stack, later to be processed by the outer consuming node visitor
  enter _ (LowerIRContext ctx@{ fn_stack }) = do
    let
      fn_context = ir_fn_context_new
      fn_stack' = (fn_context : fn_stack)
      ctx' = LowerIRContext $ merge { fn_stack: fn_stack' } ctx
    
    continue ctx'

  exit = ignore

instance type_ir_lower_fn_param_pass :: Pass FnParam (LowerIRContext u) where
  enter = ignore
  exit = ignore

instance type_ir_lower_type_expr_pass :: Pass TypeExpr (LowerIRContext u) where
  enter = ignore
  exit = ignore

instance type_ir_lower_type_expr_kind_pass :: Pass TypeExprKind (LowerIRContext u) where
  enter = ignore
  exit = ignore

instance type_ir_lower_expr_pass :: Pass Expr (LowerIRContext u) where
  enter = ignore
  exit = ignore

instance type_ir_lower_expr_kind_pass :: Pass ExprKind (LowerIRContext u) where
  enter (WhenExpr arms maybe_else) (LowerIRContext ctx@{}) = Nothing
  enter (BlockExpr body) (LowerIRContext ctx@{}) = Nothing
  enter (EqualsExpr l r) (LowerIRContext ctx@{}) = Nothing

  enter (IntExpr val) (LowerIRContext ctx@{ fn_stack: (fn_context : fn_stack), ir_stack }) = do
    let
      Tuple ir_int_const_id fn_context' = ir_int_const val fn_context
      ir_stack' = (ir_int_const_id : ir_stack)
      ctx' = LowerIRContext $ merge { ir_stack: ir_stack', fn_stack: (fn_context' : fn_stack) } ctx

    skip_all ctx'

  enter (NameExpr name) (LowerIRContext ctx@{ fn_stack }) = Nothing
  enter (CallExpr callee params) (LowerIRContext ctx@{}) = Nothing
  enter (AddExpr l r) (LowerIRContext ctx@{}) = Nothing
  enter (SubExpr l r) (LowerIRContext ctx@{}) = Nothing
  enter (MulExpr l r) (LowerIRContext ctx@{}) = Nothing
  enter (DivExpr l r) (LowerIRContext ctx@{}) = Nothing
  enter (GreaterThanExpr l r) (LowerIRContext ctx@{}) = Nothing
  enter (LessThanExpr l r) (LowerIRContext ctx@{}) = Nothing
  enter (GreaterThanEqualsExpr l r) (LowerIRContext ctx@{}) = Nothing
  enter (LessThanEqualsExpr l r) (LowerIRContext ctx@{}) = Nothing
  enter _ _ = Nothing
  exit = ignore

-- AddExpr
-- SubExpr
-- MulExpr
-- DivExpr
-- WhenExpr
-- BlockExpr
-- EqualsExpr
-- NameExpr
-- CallExpr
-- GreaterThanExpr
-- LessThanExpr
-- GreaterThanEqualsExpr
-- LessThanEqualsExpr

instance type_ir_lower_when_arm_pass :: Pass WhenArm (LowerIRContext u) where
  enter = ignore
  exit = ignore
