#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/../.."
python3 tools/dew-test/assemble.py
node tools/dew-test/run.mjs \
  --builtin-traps tools/dew-test/builtin_traps.wasm \
  --label "Dew stdlib tests" \
  "$@"
node tools/check-scalar-conversions.mjs tools/dew-test/scalar_conversions.wasm
node tools/check-memory-operations.mjs tools/dew-test/memory_operations.wasm
node tools/check-simd-memory-operations.mjs tools/dew-test/simd-memory-operations.wasm
node tools/check-arithmetic-operations.mjs tools/dew-test/arithmetic_operations.wasm
node tools/check-math-operations.mjs tools/dew-test/math_operations.wasm
node tools/check-specialization-products.mjs tools/dew-test/specialization_products.wasm
node tools/check-generic-query-order.mjs tools/dew-test/generic_query_order.wasm
node tools/check-specialization-callbacks.mjs tools/dew-test/specialization_callbacks.wasm
node tools/check-member-calls.mjs tools/dew-test/member_calls.wasm
node tools/check-wasi-foreign.mjs tools/dew-test/wasi_foreign.wasm
node tools/check-debug-dispatch.mjs tools/dew-test/debug_dispatch.wasm
node tools/check-debug-integers.mjs tools/dew-test/debug_integers.wasm
node tools/check-debug-floats.mjs tools/dew-test/debug_floats.wasm
node tools/check-debug-vectors.mjs tools/dew-test/debug_vectors.wasm
node tools/check-debug-swar.mjs tools/dew-test/debug_swar.wasm
node tools/check-debug-unit.mjs tools/dew-test/debug_unit.wasm
node tools/check-debug-bool.mjs tools/dew-test/debug_bool.wasm
node tools/check-debug-derived.mjs tools/dew-test/debug_derived.wasm
node tools/check-debug-text.mjs tools/dew-test/debug_text.wasm
node tools/check-intrinsic-names.mjs tools/dew-test/intrinsic_names.wasm
node tools/check-builtin-references.mjs tools/dew-test/intrinsic_function_reference.wasm
node tools/check-production-assertions.mjs tools/dew-test/production_assertions.wasm
node tools/check-wasi-bytes.mjs tools/dew-test/wasi_bytes.wasm
node tools/wasi-parity/check-staging.mjs tools/dew-test/wasi_staging.wasm
node tools/check-product-patterns.mjs tools/dew-test/product_patterns.wasm
node tools/check-constructor-evaluations.mjs tools/dew-test/constructor_evaluations.wasm
node tools/check-unit-branches.mjs tools/dew-test/unit_branches.wasm
node tools/check-raw-gc-storage.mjs tools/dew-test/raw_gc_storage.wasm
node tools/check-raw-gc-unit.mjs tools/dew-test/raw_gc_unit.wasm
node tools/check-fixed-array-operations.mjs tools/dew-test/fixed_array_operations.wasm
node tools/check-raw-array-contracts.mjs tools/dew-test/raw_array_contracts.wasm
node tools/check-packed-fields.mjs tools/dew-test/packed_fields.wasm
node tools/check-array-operations.mjs tools/dew-test/array_operations.wasm
node tools/check-ring-operations.mjs tools/dew-test/ring_operations.wasm
node tools/check-map-operations.mjs tools/dew-test/map_operations.wasm
node tools/check-set-operations.mjs tools/dew-test/set_operations.wasm
node tools/check-bytes-operations.mjs tools/dew-test/bytes_operations.wasm
node tools/check-string-view-operations.mjs tools/dew-test/string_view_operations.wasm
node tools/check-string-operations.mjs tools/dew-test/string_operations.wasm
node tools/check-string-patterns.mjs tools/dew-test/string_patterns.wasm
node tools/check-type-queries.mjs tools/dew-test/type_queries.wasm
