#!/usr/bin/env python3
"""Generate deterministic strict UTF-8 differential cases."""

from __future__ import annotations

import json
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parent
RNG = random.Random(0x55544638)


def dew_literal(data: bytes, *, bytes_: bool) -> str:
    prefix = "b" if bytes_ else ""
    return prefix + '"' + "".join(f"\\x{byte:02X}" for byte in data) + '"'


def utf16_units(text: str) -> int:
    return len(text.encode("utf-16-le")) // 2


def main() -> None:
    cases: list[bytes] = []
    valid_samples = [
        "", "ASCII", "λ", "世界", "🌍", "aλ🌍", "हिन्दी", "😀🧪",
        "x" * 15 + "λ", "x" * 15 + "世", "x" * 15 + "🌍",
    ]
    cases.extend(text.encode("utf-8") for text in valid_samples)
    # Exhaust every possible one-byte input, then force valid and malformed
    # sequences to begin at every position around two adjacent V128 chunks.
    cases.extend(bytes([byte]) for byte in range(256))
    for prefix_length in range(32):
        prefix = b"a" * prefix_length
        cases.extend([
            prefix + b"\xC2\xA2",
            prefix + b"\xE2\x82\xAC",
            prefix + b"\xF0\x9F\x8C\x8D",
            prefix + b"\xC2A",
            prefix + b"\xE0\x9F\x80",
            prefix + b"\xED\xA0\x80",
            prefix + b"\xF0\x8F\xBF\xBF",
            prefix + b"\xF4\x90\x80\x80",
            prefix + b"\xE2\x82",
            prefix + b"\xF0\x9F\x8C",
        ])
    for _ in range(256):
        length = RNG.randrange(0, 49)
        cases.append(bytes(RNG.randrange(256) for _ in range(length)))
    for _ in range(128):
        length = RNG.randrange(0, 49)
        text = "".join(chr(RNG.choice([
            RNG.randrange(0x20, 0x7F), RNG.randrange(0x80, 0x800),
            RNG.randrange(0x800, 0xD800), RNG.randrange(0xE000, 0x10000),
            RNG.randrange(0x10000, 0x110000),
        ])) for _ in range(length))
        cases.append(text.encode("utf-8"))

    source = ["// Generated by tools/utf-parity/generate_cases.py.\n"]
    expected = []
    for index, data in enumerate(cases):
        try:
            text = data.decode("utf-8", errors="strict")
            valid = True
            units = utf16_units(text)
        except UnicodeDecodeError:
            valid = False
            units = None
        bytes_literal = dew_literal(data, bytes_=True)
        source.append(
            f"pub fn generated_valid_{index}() -> Bool {{\n  {bytes_literal}.is_valid_utf8()\n}}\n"
        )
        if valid:
            source.append(
                f"pub fn generated_units_{index}() -> U32 {{\n"
                f"  {bytes_literal}.to_string().utf16_length()\n}}\n"
            )
        probes: list[dict[str, int]] = []
        if index < 96:
            source.append(
                f"pub fn generated_equal_{index}() -> Bool {{\n"
                f"  {bytes_literal}.equals({bytes_literal})\n}}\n"
            )
            if data:
                changed = bytearray(data)
                changed[len(changed) // 2] ^= 1
                unequal = bytes(changed)
            else:
                unequal = b"\\x00"
            source.append(
                f"pub fn generated_unequal_{index}() -> Bool {{\n"
                f"  {bytes_literal}.equals({dew_literal(unequal, bytes_=True)})\n}}\n"
            )
            if data:
                for probe_index in sorted({0, len(data) // 2, len(data) - 1}):
                    source.append(
                        f"pub fn generated_byte_{index}_{probe_index}() -> U8 {{\n"
                        f"  {bytes_literal}.byte_at({probe_index}u32)\n}}\n"
                    )
                    probes.append({"offset": probe_index, "value": data[probe_index]})
        view = valid
        builder = valid and index < 160
        bytes_builder = index < 320
        bytes_range = index < 128
        string_range = valid and index < 128
        checked_builder = valid and index < 320
        bytes_concat = index < 320
        bytes_search = index < 192
        bytes_substring_search = index < 192
        string_concat = valid and index < 192
        nested_view = valid and index < 160
        view_start = index % 16
        if view:
            wrapped = b"x" * view_start + data + b"y"
            wrapped_literal = dew_literal(wrapped, bytes_=False)
            text_literal = dew_literal(data, bytes_=False)
            source.append(
                f"pub fn generated_view_equal_{index}() -> Bool {{\n"
                f"  {wrapped_literal}.view({view_start}u32, {len(data)}u32).to_string().equals({text_literal})\n"
                f"}}\n"
            )
            source.append(
                f"pub fn generated_view_bytes_{index}() -> Bool {{\n"
                f"  {wrapped_literal}.view({view_start}u32, {len(data)}u32).as_bytes().equals({bytes_literal})\n"
                f"}}\n"
            )
            source.append(
                f"pub fn generated_view_units_{index}() -> U32 {{\n"
                f"  {wrapped_literal}.view({view_start}u32, {len(data)}u32).utf16_length()\n"
                f"}}\n"
            )
        if nested_view:
            nested_prefix = b"q" + b"x" * view_start
            nested_source = nested_prefix + data + b"z"
            source.append(
                f"pub fn generated_nested_view_{index}() -> Bool {{\n"
                f"  {dew_literal(nested_source, bytes_=False)}"
                f".view(1u32, {view_start + len(data)}u32)"
                f".view({view_start}u32, {len(data)}u32)"
                f".to_string().equals({dew_literal(data, bytes_=False)})\n"
                f"}}\n"
            )
        if builder:
            wrapped = b"x" * view_start + data + b"y"
            expected_builder = b"left-" + data + b"-right"
            source.append(
                f"pub fn generated_builder_{index}() -> Bool {{\n"
                f"  let builder = StringBuilder::with_capacity({index % 33}u32)\n"
                f"  builder.append(\"left-\")\n"
                f"  builder.append_view({dew_literal(wrapped, bytes_=False)}.view({view_start}u32, {len(data)}u32))\n"
                f"  builder.append(\"-right\")\n"
                f"  builder.finish().equals({dew_literal(expected_builder, bytes_=False)})\n"
                f"}}\n"
            )
        if bytes_range:
            wrapped_bytes = b"\xAA" + data + b"\xBB"
            wrapped_bytes_literal = dew_literal(wrapped_bytes, bytes_=True)
            range_end = 1 + len(data)
            for operation, expression in [
                ("view", f"{wrapped_bytes_literal}.view(1u32, {len(data)}u32)"),
                ("subarray", f"{wrapped_bytes_literal}.subarray(1u32, {range_end}u32)"),
                ("slice", f"{wrapped_bytes_literal}.slice(1u32, {range_end}u32)"),
                ("compact", f"{wrapped_bytes_literal}.view(1u32, {len(data)}u32).compact()"),
            ]:
                source.append(
                    f"pub fn generated_bytes_{operation}_{index}() -> Bool {{\n"
                    f"  {expression}.equals({bytes_literal})\n"
                    f"}}\n"
                )
        if string_range:
            wrapped_text = b"x" + data + b"y"
            wrapped_text_literal = dew_literal(wrapped_text, bytes_=False)
            range_end = 1 + len(data)
            text_literal = dew_literal(data, bytes_=False)
            for operation, expression in [
                ("subarray", f"{wrapped_text_literal}.subarray(1u32, {range_end}u32).to_string()"),
                ("slice", f"{wrapped_text_literal}.slice(1u32, {range_end}u32)"),
                ("compact", f"{wrapped_text_literal}.view(1u32, {len(data)}u32).compact()"),
            ]:
                source.append(
                    f"pub fn generated_string_{operation}_{index}() -> Bool {{\n"
                    f"  {expression}.equals({text_literal})\n"
                    f"}}\n"
                )
        if bytes_search:
            search_start = (index * 5 + 1) % 16
            search_wrapped = b"s" * search_start + data + b"S"
            search_value = (
                f"{dew_literal(search_wrapped, bytes_=True)}"
                f".view({search_start}u32, {len(data)}u32)"
            )
            present_byte = data[len(data) // 2] if data else 0
            present_index = data.find(bytes([present_byte]))
            absent_byte = next(byte for byte in range(256) if byte not in data)
            split = len(data) // 2
            prefix = data[:split]
            suffix = data[split:]
            source.append(
                f"pub fn generated_find_byte_{index}() -> U32 {{\n"
                f"  match {search_value}.find_byte({present_byte}u8) {{\n"
                f"    Option::Some(found) => found\n"
                f"    Option::None => 4294967295u32\n"
                f"  }}\n"
                f"}}\n"
            )
            source.append(
                f"pub fn generated_find_absent_{index}() -> Bool {{\n"
                f"  match {search_value}.find_byte({absent_byte}u8) {{\n"
                f"    Option::Some(_) => false\n"
                f"    Option::None => true\n"
                f"  }}\n"
                f"}}\n"
            )
            contains_expression = (
                f"{search_value}.contains_byte({present_byte}u8)"
                if data
                else f"!{search_value}.contains_byte({present_byte}u8)"
            )
            source.append(
                f"pub fn generated_contains_byte_{index}() -> Bool {{\n"
                f"  {contains_expression}\n"
                f"}}\n"
            )
            source.append(
                f"pub fn generated_starts_with_{index}() -> Bool {{\n"
                f"  {search_value}.starts_with({dew_literal(prefix, bytes_=True)})\n"
                f"}}\n"
            )
            source.append(
                f"pub fn generated_ends_with_{index}() -> Bool {{\n"
                f"  {search_value}.ends_with({dew_literal(suffix, bytes_=True)})\n"
                f"}}\n"
            )
        else:
            present_index = -1
        if bytes_substring_search:
            substring_start = (index * 13 + 7) % 16
            substring_wrapped = b"h" * substring_start + data + b"H"
            substring_value = (
                f"{dew_literal(substring_wrapped, bytes_=True)}"
                f".view({substring_start}u32, {len(data)}u32)"
            )
            if data:
                selected_start = (index * 3) % len(data)
                available = len(data) - selected_start
                selected_length = min(available, max(1, (index % 23) + 1))
                needle = data[selected_start:selected_start + selected_length]
            else:
                needle = b""
            substring_index = data.find(needle)
            overlong = data + bytes([(index * 17 + 1) % 256])
            source.append(
                f"pub fn generated_find_substring_{index}() -> U32 {{\n"
                f"  match {substring_value}.find({dew_literal(needle, bytes_=True)}) {{\n"
                f"    Option::Some(found) => found\n"
                f"    Option::None => 4294967295u32\n"
                f"  }}\n"
                f"}}\n"
            )
            source.append(
                f"pub fn generated_contains_substring_{index}() -> Bool {{\n"
                f"  {substring_value}.contains({dew_literal(needle, bytes_=True)})\n"
                f"}}\n"
            )
            source.append(
                f"pub fn generated_find_overlong_{index}() -> Bool {{\n"
                f"  match {substring_value}.find({dew_literal(overlong, bytes_=True)}) {{\n"
                f"    Option::Some(_) => false\n"
                f"    Option::None => true\n"
                f"  }}\n"
                f"}}\n"
            )
        else:
            substring_index = -1
        if bytes_concat:
            split = len(data) // 2
            left_data = data[:split]
            right_data = data[split:]
            left_start = index % 16
            right_start = (index * 7 + 3) % 16
            left_wrapped = b"l" * left_start + left_data + b"L"
            right_wrapped = b"r" * right_start + right_data + b"R"
            source.append(
                f"pub fn generated_bytes_concat_{index}() -> Bool {{\n"
                f"  {dew_literal(left_wrapped, bytes_=True)}.view({left_start}u32, {len(left_data)}u32)"
                f".concat({dew_literal(right_wrapped, bytes_=True)}.view({right_start}u32, {len(right_data)}u32))"
                f".equals({bytes_literal})\n"
                f"}}\n"
            )
        if string_concat:
            split_scalars = len(text) // 2
            left_data = text[:split_scalars].encode("utf-8")
            right_data = text[split_scalars:].encode("utf-8")
            left_start = index % 16
            right_start = (index * 11 + 5) % 16
            left_wrapped = b"l" * left_start + left_data + b"L"
            right_wrapped = b"r" * right_start + right_data + b"R"
            left_expression = (
                f"{dew_literal(left_wrapped, bytes_=False)}"
                f".view({left_start}u32, {len(left_data)}u32).to_string()"
            )
            right_view = (
                f"{dew_literal(right_wrapped, bytes_=False)}"
                f".view({right_start}u32, {len(right_data)}u32)"
            )
            source.append(
                f"pub fn generated_string_concat_{index}() -> Bool {{\n"
                f"  {left_expression}.concat({right_view}.to_string())"
                f".equals({dew_literal(data, bytes_=False)})\n"
                f"}}\n"
            )
            source.append(
                f"pub fn generated_string_concat_view_{index}() -> Bool {{\n"
                f"  {left_expression}.concat_view({right_view})"
                f".equals({dew_literal(data, bytes_=False)})\n"
                f"}}\n"
            )
        if checked_builder:
            source.append(
                f"pub fn generated_checked_builder_{index}() -> Bool {{\n"
                f"  let builder = StringBuilder::with_capacity({index % 17}u32)\n"
                f"  builder.append_checked({bytes_literal})\n"
                f"  builder.finish().as_bytes().equals({bytes_literal})\n"
                f"}}\n"
            )
        if bytes_builder:
            split = len(data) // 2
            left = data[:split]
            if split < len(data):
                middle = data[split]
                right = data[split + 1:]
                middle_append = f"  builder.append_byte({middle}u8)\n"
            else:
                right = b""
                middle_append = ""
            source.append(
                f"pub fn generated_bytes_builder_{index}() -> Bool {{\n"
                f"  let builder = BytesBuilder::with_capacity({index % 25}u32)\n"
                f"  builder.append({dew_literal(left, bytes_=True)})\n"
                f"{middle_append}"
                f"  builder.append({dew_literal(right, bytes_=True)})\n"
                f"  builder.finish().equals({bytes_literal})\n"
                f"}}\n"
            )
        conversion_trap = not valid and index < 320
        if conversion_trap:
            source.append(
                f"pub fn generated_conversion_trap_{index}() -> U32 {{\n"
                f"  {bytes_literal}.to_string().byte_length()\n}}\n"
            )
        expected.append({
            "index": index, "valid": valid, "units": units,
            "equality": index < 96, "probes": probes,
            "view": view, "builder": builder, "bytes_builder": bytes_builder,
            "bytes_range": bytes_range, "string_range": string_range,
            "checked_builder": checked_builder, "bytes_concat": bytes_concat,
            "bytes_search": bytes_search, "present_index": present_index,
            "bytes_substring_search": bytes_substring_search,
            "substring_index": substring_index,
            "string_concat": string_concat, "nested_view": nested_view,
            "conversion_trap": conversion_trap,
        })

    for byte in range(128):
        source.append(
            f"pub fn generated_ascii_builder_{byte}() -> Bool {{\n"
            f"  let builder = StringBuilder::with_capacity(0u32)\n"
            f"  builder.append_ascii({byte}u8)\n"
            f"  builder.finish().as_bytes().equals({dew_literal(bytes([byte]), bytes_=True)})\n"
            f"}}\n"
        )

    scalar_values = [
        0x0000, 0x0001, 0x007F, 0x0080, 0x07FF, 0x0800,
        0xD7FF, 0xE000, 0xFFFF, 0x10000, 0x10FFFF,
    ]
    while len(scalar_values) < 267:
        scalar = RNG.randrange(0x110000)
        if 0xD800 <= scalar <= 0xDFFF or scalar in scalar_values:
            continue
        scalar_values.append(scalar)
    for index, scalar in enumerate(scalar_values):
        encoded = chr(scalar).encode("utf-8")
        source.append(
            f"pub fn generated_scalar_builder_{index}() -> Bool {{\n"
            f"  let builder = StringBuilder::with_capacity({index % 9}u32)\n"
            f"  builder.append_scalar({scalar}u32)\n"
            f"  builder.finish().as_bytes().equals({dew_literal(encoded, bytes_=True)})\n"
            f"}}\n"
        )

    all_bytes = bytes(range(256))
    for alignment in range(16):
        wrapped = b"p" * alignment + all_bytes + b"q"
        source.append(
            f"pub fn generated_find_all_bytes_alignment_{alignment}(byte: U8) -> U32 {{\n"
            f"  match {dew_literal(wrapped, bytes_=True)}.view({alignment}u32, 256u32).find_byte(byte) {{\n"
            f"    Option::Some(found) => found\n"
            f"    Option::None => 4294967295u32\n"
            f"  }}\n"
            f"}}\n"
        )

    substring_lengths = [0, 1, 2, 3, 7, 8, 15, 16, 17, 18, 31, 32, 33, 63, 64, 65]
    substring_positions = [0, 1, 15, 16, 17, 31, 32, 63]
    for alignment in range(16):
        for length_index, needle_length in enumerate(substring_lengths):
            needle = bytes(
                ((offset * 37 + needle_length * 11 + 1) % 255) + 1
                for offset in range(needle_length)
            )
            for position_index, position in enumerate(substring_positions):
                logical = b"\x00" * position + needle + b"\x00" * 8
                wrapped = b"h" * alignment + logical + b"H"
                expected_index = 0 if needle_length == 0 else position
                source.append(
                    f"pub fn generated_substring_matrix_{alignment}_{length_index}_{position_index}() -> U32 {{\n"
                    f"  match {dew_literal(wrapped, bytes_=True)}.view({alignment}u32, {len(logical)}u32)"
                    f".find({dew_literal(needle, bytes_=True)}) {{\n"
                    f"    Option::Some(found) => found\n"
                    f"    Option::None => 4294967295u32\n"
                    f"  }}\n"
                    f"}}\n"
                )
                assert expected_index == logical.find(needle)
            absent_haystack = b"\x00" * (needle_length + 72)
            absent_wrapped = b"a" * alignment + absent_haystack + b"A"
            absent_needle = needle if needle else b"\x01"
            source.append(
                f"pub fn generated_substring_absent_{alignment}_{length_index}() -> Bool {{\n"
                f"  match {dew_literal(absent_wrapped, bytes_=True)}"
                f".view({alignment}u32, {len(absent_haystack)}u32)"
                f".find({dew_literal(absent_needle, bytes_=True)}) {{\n"
                f"    Option::Some(_) => false\n"
                f"    Option::None => true\n"
                f"  }}\n"
                f"}}\n"
            )

    text_match_positions = [0, 1, 15, 16, 17, 31, 32, 63]
    text_match_needles = [
        "λ世界".encode("utf-8"),
        "λ世界🌍-repeated-λ".encode("utf-8"),
    ]
    for alignment in range(16):
        needle_alignment = (alignment * 7 + 3) % 16
        for pattern_index, text_needle in enumerate(text_match_needles):
            needle_backing = b"n" * needle_alignment + text_needle + b"N"
            needle_view = (
                f"{dew_literal(needle_backing, bytes_=False)}"
                f".view({needle_alignment}u32, {len(text_needle)}u32)"
            )
            for position_index, position in enumerate(text_match_positions):
                haystack = b"a" * position + text_needle + b" tail"
                haystack_backing = b"h" * alignment + haystack + b"H"
                haystack_view = (
                    f"{dew_literal(haystack_backing, bytes_=False)}"
                    f".view({alignment}u32, {len(haystack)}u32)"
                )
                prefix_haystack = text_needle + b" suffix"
                prefix_backing = b"p" * alignment + prefix_haystack + b"P"
                prefix_view = (
                    f"{dew_literal(prefix_backing, bytes_=False)}"
                    f".view({alignment}u32, {len(prefix_haystack)}u32)"
                )
                suffix_haystack = b"prefix " + text_needle
                suffix_backing = b"s" * alignment + suffix_haystack + b"S"
                suffix_view = (
                    f"{dew_literal(suffix_backing, bytes_=False)}"
                    f".view({alignment}u32, {len(suffix_haystack)}u32)"
                )
                base_name = f"{alignment}_{pattern_index}_{position_index}"
                source.append(
                    f"pub fn generated_text_find_matrix_{base_name}() -> U32 {{\n"
                    f"  let hay_view = {haystack_view}\n"
                    f"  let hay_string = hay_view.to_string()\n"
                    f"  let needle_view = {needle_view}\n"
                    f"  let needle_string = needle_view.to_string()\n"
                    f"  let a = match hay_string.find(needle_string) {{\n"
                    f"    Option::Some(found) => found\n"
                    f"    Option::None => 4294967295u32\n"
                    f"  }}\n"
                    f"  let b = match hay_string.find_view(needle_view) {{\n"
                    f"    Option::Some(found) => found\n"
                    f"    Option::None => 4294967295u32\n"
                    f"  }}\n"
                    f"  let c = match hay_view.find(needle_view) {{\n"
                    f"    Option::Some(found) => found\n"
                    f"    Option::None => 4294967295u32\n"
                    f"  }}\n"
                    f"  let d = match hay_view.find_string(needle_string) {{\n"
                    f"    Option::Some(found) => found\n"
                    f"    Option::None => 4294967295u32\n"
                    f"  }}\n"
                    f"  a + b + c + d\n"
                    f"}}\n"
                )
                source.append(
                    f"pub fn generated_text_contains_matrix_{base_name}() -> U32 {{\n"
                    f"  let hay_view = {haystack_view}\n"
                    f"  let hay_string = hay_view.to_string()\n"
                    f"  let needle_view = {needle_view}\n"
                    f"  let needle_string = needle_view.to_string()\n"
                    f"  let a = if hay_string.contains(needle_string) {{\n    1u32\n  }} else {{\n    0u32\n  }}\n"
                    f"  let b = if hay_string.contains_view(needle_view) {{\n    1u32\n  }} else {{\n    0u32\n  }}\n"
                    f"  let c = if hay_view.contains(needle_view) {{\n    1u32\n  }} else {{\n    0u32\n  }}\n"
                    f"  let d = if hay_view.contains_string(needle_string) {{\n    1u32\n  }} else {{\n    0u32\n  }}\n"
                    f"  a + b + c + d\n"
                    f"}}\n"
                )
                source.append(
                    f"pub fn generated_text_starts_matrix_{base_name}() -> U32 {{\n"
                    f"  let hay_view = {prefix_view}\n"
                    f"  let hay_string = hay_view.to_string()\n"
                    f"  let needle_view = {needle_view}\n"
                    f"  let needle_string = needle_view.to_string()\n"
                    f"  let a = if hay_string.starts_with(needle_string) {{\n    1u32\n  }} else {{\n    0u32\n  }}\n"
                    f"  let b = if hay_string.starts_with_view(needle_view) {{\n    1u32\n  }} else {{\n    0u32\n  }}\n"
                    f"  let c = if hay_view.starts_with(needle_view) {{\n    1u32\n  }} else {{\n    0u32\n  }}\n"
                    f"  let d = if hay_view.starts_with_string(needle_string) {{\n    1u32\n  }} else {{\n    0u32\n  }}\n"
                    f"  a + b + c + d\n"
                    f"}}\n"
                )
                source.append(
                    f"pub fn generated_text_ends_matrix_{base_name}() -> U32 {{\n"
                    f"  let hay_view = {suffix_view}\n"
                    f"  let hay_string = hay_view.to_string()\n"
                    f"  let needle_view = {needle_view}\n"
                    f"  let needle_string = needle_view.to_string()\n"
                    f"  let a = if hay_string.ends_with(needle_string) {{\n    1u32\n  }} else {{\n    0u32\n  }}\n"
                    f"  let b = if hay_string.ends_with_view(needle_view) {{\n    1u32\n  }} else {{\n    0u32\n  }}\n"
                    f"  let c = if hay_view.ends_with(needle_view) {{\n    1u32\n  }} else {{\n    0u32\n  }}\n"
                    f"  let d = if hay_view.ends_with_string(needle_string) {{\n    1u32\n  }} else {{\n    0u32\n  }}\n"
                    f"  a + b + c + d\n"
                    f"}}\n"
                )
                absent = "不存在🌑".encode("utf-8")
                absent_backing = b"x" * needle_alignment + absent + b"X"
                absent_view = (
                    f"{dew_literal(absent_backing, bytes_=False)}"
                    f".view({needle_alignment}u32, {len(absent)}u32)"
                )
                source.append(
                    f"pub fn generated_text_absent_matrix_{base_name}() -> U32 {{\n"
                    f"  let hay_view = {haystack_view}\n"
                    f"  let hay_string = hay_view.to_string()\n"
                    f"  let needle_view = {absent_view}\n"
                    f"  let needle_string = needle_view.to_string()\n"
                    f"  let a = match hay_string.find(needle_string) {{\n"
                    f"    Option::None => 1u32\n"
                    f"    _ => 0u32\n"
                    f"  }}\n"
                    f"  let b = match hay_string.find_view(needle_view) {{\n"
                    f"    Option::None => 1u32\n"
                    f"    _ => 0u32\n"
                    f"  }}\n"
                    f"  let c = match hay_view.find(needle_view) {{\n"
                    f"    Option::None => 1u32\n"
                    f"    _ => 0u32\n"
                    f"  }}\n"
                    f"  let d = match hay_view.find_string(needle_string) {{\n"
                    f"    Option::None => 1u32\n"
                    f"    _ => 0u32\n"
                    f"  }}\n"
                    f"  a + b + c + d\n"
                    f"}}\n"
                )

    collision_prefix = b"collision"
    collision_suffix = bytes([249, 27, 201, 69, 201, 27, 249, 1])
    collision_needle = collision_prefix + collision_suffix
    collision_window = collision_prefix + b"\x00" * 8
    collision_haystack = collision_window + b"~" + collision_needle
    source.append(
        f"pub fn generated_rolling_hash_collision() -> U32 {{\n"
        f"  match {dew_literal(collision_haystack, bytes_=True)}.find({dew_literal(collision_needle, bytes_=True)}) {{\n"
        f"    Option::Some(found) => found\n"
        f"    Option::None => 4294967295u32\n"
        f"  }}\n"
        f"}}\n"
    )

    concat_lengths = [0, 1, 15, 16, 17, 31, 32, 33]
    for alignment_pair in range(16):
        left_start = alignment_pair
        right_start = (alignment_pair * 7 + 3) % 16
        for left_index, left_length in enumerate(concat_lengths):
            left = bytes((offset * 31 + left_length * 5 + 1) % 256 for offset in range(left_length))
            left_wrapped = b"l" * left_start + left + b"L"
            for right_index, right_length in enumerate(concat_lengths):
                right = bytes((offset * 43 + right_length * 9 + 3) % 256 for offset in range(right_length))
                right_wrapped = b"r" * right_start + right + b"R"
                source.append(
                    f"pub fn generated_concat_boundary_{alignment_pair}_{left_index}_{right_index}() -> Bool {{\n"
                    f"  {dew_literal(left_wrapped, bytes_=True)}.view({left_start}u32, {left_length}u32)"
                    f".concat({dew_literal(right_wrapped, bytes_=True)}.view({right_start}u32, {right_length}u32))"
                    f".equals({dew_literal(left + right, bytes_=True)})\n"
                    f"}}\n"
                )

    range_lengths = [0, 1, 15, 16, 17, 31, 32, 33, 63, 64, 65]
    for alignment in range(16):
        for length_index, length in enumerate(range_lengths):
            data = bytes((offset * 47 + length * 3 + 1) % 256 for offset in range(length))
            wrapped = b"b" * alignment + data + b"B"
            wrapped_literal = dew_literal(wrapped, bytes_=True)
            data_literal = dew_literal(data, bytes_=True)
            end = alignment + length
            for operation, expression in [
                ("view", f"{wrapped_literal}.view({alignment}u32, {length}u32)"),
                ("subarray", f"{wrapped_literal}.subarray({alignment}u32, {end}u32)"),
                ("slice", f"{wrapped_literal}.slice({alignment}u32, {end}u32)"),
                ("compact", f"{wrapped_literal}.view({alignment}u32, {length}u32).compact()"),
            ]:
                source.append(
                    f"pub fn generated_bytes_range_boundary_{operation}_{alignment}_{length_index}() -> Bool {{\n"
                    f"  {expression}.equals({data_literal})\n"
                    f"}}\n"
                )
            ascii_data = bytes(32 + (byte % 95) for byte in data)
            text_wrapped = b"t" * alignment + ascii_data + b"T"
            text_wrapped_literal = dew_literal(text_wrapped, bytes_=False)
            text_literal = dew_literal(ascii_data, bytes_=False)
            for operation, expression in [
                ("subarray", f"{text_wrapped_literal}.subarray({alignment}u32, {end}u32).to_string()"),
                ("slice", f"{text_wrapped_literal}.slice({alignment}u32, {end}u32)"),
                ("compact", f"{text_wrapped_literal}.view({alignment}u32, {length}u32).compact()"),
            ]:
                source.append(
                    f"pub fn generated_string_range_boundary_{operation}_{alignment}_{length_index}() -> Bool {{\n"
                    f"  {expression}.equals({text_literal})\n"
                    f"}}\n"
                )

    boundary_scalars = ["λ".encode("utf-8"), "世".encode("utf-8"), "🌍".encode("utf-8")]
    for alignment in range(16):
        for scalar_index, scalar in enumerate(boundary_scalars):
            backing = b"u" * alignment + scalar + b"v"
            for interior in range(1, len(scalar)):
                source.append(
                    f"pub fn generated_utf_boundary_start_trap_{alignment}_{scalar_index}_{interior}() -> U32 {{\n"
                    f"  {dew_literal(backing, bytes_=False)}"
                    f".view({alignment + interior}u32, {len(scalar) - interior}u32).byte_length()\n"
                    f"}}\n"
                )
                source.append(
                    f"pub fn generated_utf_boundary_end_trap_{alignment}_{scalar_index}_{interior}() -> U32 {{\n"
                    f"  {dew_literal(backing, bytes_=False)}"
                    f".view({alignment}u32, {interior}u32).byte_length()\n"
                    f"}}\n"
                )

    builder_lengths = [0, 1, 15, 16, 17, 31, 32, 33, 63, 64, 65]
    builder_capacities = [0, 1, 15, 16, 17, 31, 32, 33]
    for capacity_index, capacity in enumerate(builder_capacities):
        for length_index, length in enumerate(builder_lengths):
            data = bytes((offset * 29 + length * 7) % 256 for offset in range(length))
            split = length // 2
            source.append(
                f"pub fn generated_bytes_builder_boundary_{capacity_index}_{length_index}() -> Bool {{\n"
                f"  let builder = BytesBuilder::with_capacity({capacity}u32)\n"
                f"  builder.append({dew_literal(data[:split], bytes_=True)})\n"
                f"  builder.append({dew_literal(data[split:], bytes_=True)})\n"
                f"  builder.finish().equals({dew_literal(data, bytes_=True)})\n"
                f"}}\n"
            )
            ascii_data = bytes(32 + (byte % 95) for byte in data)
            source.append(
                f"pub fn generated_string_builder_boundary_{capacity_index}_{length_index}() -> Bool {{\n"
                f"  let builder = StringBuilder::with_capacity({capacity}u32)\n"
                f"  builder.append({dew_literal(ascii_data[:split], bytes_=False)})\n"
                f"  builder.append({dew_literal(ascii_data[split:], bytes_=False)})\n"
                f"  builder.finish().as_bytes().equals({dew_literal(ascii_data, bytes_=True)})\n"
                f"}}\n"
            )

    stress_haystack = b"a" * 65535 + b"Z"
    stress_needle = b"a" * 31 + b"Z"
    stress_absent = b"a" * 31 + b"Y"
    source.append(
        f"pub fn generated_large_search_present() -> U32 {{\n"
        f"  match {dew_literal(stress_haystack, bytes_=True)}.find({dew_literal(stress_needle, bytes_=True)}) {{\n"
        f"    Option::Some(found) => found\n"
        f"    Option::None => 4294967295u32\n"
        f"  }}\n"
        f"}}\n"
    )
    source.append(
        f"pub fn generated_large_search_absent() -> Bool {{\n"
        f"  match {dew_literal(stress_haystack, bytes_=True)}.find({dew_literal(stress_absent, bytes_=True)}) {{\n"
        f"    Option::Some(_) => false\n"
        f"    Option::None => true\n"
        f"  }}\n"
        f"}}\n"
    )
    stress_builder = bytes((offset * 73 + 19) % 256 for offset in range(4096))
    source.append(
        f"pub fn generated_large_bytes_builder() -> Bool {{\n"
        f"  let builder = BytesBuilder::with_capacity(1u32)\n"
        f"  builder.append({dew_literal(stress_builder[:2048], bytes_=True)})\n"
        f"  builder.append({dew_literal(stress_builder[2048:], bytes_=True)})\n"
        f"  builder.finish().equals({dew_literal(stress_builder, bytes_=True)})\n"
        f"}}\n"
    )
    stress_ascii = bytes(32 + (byte % 95) for byte in stress_builder)
    source.append(
        f"pub fn generated_large_string_builder() -> Bool {{\n"
        f"  let builder = StringBuilder::with_capacity(1u32)\n"
        f"  builder.append({dew_literal(stress_ascii[:2048], bytes_=False)})\n"
        f"  builder.append({dew_literal(stress_ascii[2048:], bytes_=False)})\n"
        f"  builder.finish().as_bytes().equals({dew_literal(stress_ascii, bytes_=True)})\n"
        f"}}\n"
    )

    (ROOT / "generated_cases.dew").write_text("".join(source), encoding="utf-8")
    (ROOT / "generated_expected.json").write_text(json.dumps(expected), encoding="utf-8")
    (ROOT / "generated_builder_expected.json").write_text(
        json.dumps({
            "ascii_count": 128,
            "scalar_count": len(scalar_values),
            "byte_alignment_count": 16,
            "substring_lengths": substring_lengths,
            "substring_positions": substring_positions,
            "text_match_positions": text_match_positions,
            "text_match_pattern_count": len(text_match_needles),
            "collision_index": len(collision_window) + 1,
            "concat_lengths": concat_lengths,
            "range_lengths": range_lengths,
            "boundary_scalar_lengths": [len(scalar) for scalar in boundary_scalars],
            "builder_lengths": builder_lengths,
            "builder_capacities": builder_capacities,
            "large_search_index": len(stress_haystack) - len(stress_needle),
        }),
        encoding="utf-8",
    )
    print(f"generated {len(cases)} UTF cases")


if __name__ == "__main__":
    main()
