#!/usr/bin/env python3
"""Generate compiler-owned standard identity and typed builtin-operation registry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "tools" / "standard-builtin-registry.json"
TARGET = ROOT / "src" / "semantic" / "standard_builtin_registry.mbt"


def if_multiline_operation_signature(prefix: str) -> list[str]:
    signature = f"fn {prefix}_operation(declaration : DeclId) -> StandardBuiltinOperation {{"
    if len(signature) <= 80:
        return [signature]
    return [
        f"fn {prefix}_operation(",
        "  declaration : DeclId,",
        ") -> StandardBuiltinOperation {",
    ]


def rendered_source() -> str:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    modules = data["modules"]
    operation_names = [
        name
        for module in (
            "wasm_intrinsics", "fixed_array", "array", "queue", "circular_buffer", "deque", "map", "set"
        )
        for name in modules[module]["operations"]
    ]
    lines = [
        "// Generated by tools/generate_standard_builtin_registry.py. Do not edit.",
        "",
        "///|",
        "enum StandardBuiltinOperation {",
        "  NoStandardBuiltinOperation",
    ]
    lines.extend(f"  {name}" for name in operation_names)
    lines.extend(["} derive(Eq, Debug)", ""])

    indexed_traits = data["preamble_traits"]
    lines.extend(
        [
            "///|",
            "fn standard_indexed_trait_kind(declaration : DeclId) -> Int {",
            "  match semantic_id_local(declaration) {",
            f"    {indexed_traits['indexed_get']} => 1",
            f"    {indexed_traits['indexed_set']} => 2",
            "    _ => 0",
            "  }",
            "}",
            "",
        ]
    )

    for module_name in (
        "fixed_array", "array", "queue", "circular_buffer", "deque", "map", "set"
    ):
        module = modules[module_name]
        prefix = f"standard_{module_name}"
        lines.extend(
            [
                "///|",
                f"pub fn {prefix}_type_declaration() -> DeclId {{",
                f"  make_semantic_id(standard_library_module_id({module.get('type_slot', module['slot'])}), {module['type']})",
                "}",
                "",
                "///|",
                f"pub fn {prefix}_method_declaration(name : String) -> DeclId {{",
                "  let local_id = match name {",
            ]
        )
        for name, ordinal in module["methods"].items():
            lines.append(f'    "{name}" => {ordinal}')
        lines.extend(
            [
                "    _ => -1",
                "  }",
                "  if local_id < 0 {",
                "    0UL",
                "  } else {",
                f"    make_semantic_id(standard_library_module_id({module['slot']}), local_id)",
                "  }",
                "}",
                "",
            ]
        )
        if "iterator_type" in module:
            lines.extend(
                [
                    "///|",
                    f"pub fn {prefix}_iterator_type_declaration() -> DeclId {{",
                    f"  make_semantic_id(standard_library_module_id({module['slot']}), {module['iterator_type']})",
                    "}",
                    "",
                ]
            )
        for opaque_name, opaque_local in module.get("opaque_types", {}).items():
            lines.extend(
                [
                    "///|",
                    f"pub fn {prefix}_{opaque_name}_type_declaration() -> DeclId {{",
                    f"  make_semantic_id(standard_library_module_id({module['slot']}), {opaque_local})",
                    "}",
                    "",
                ]
            )
        if "index" in module:
            lines.extend(
                [
                    "///|",
                    f"pub fn {prefix}_index_declaration() -> DeclId {{",
                    f"  make_semantic_id(standard_library_module_id({module['slot']}), {module['index']})",
                    "}",
                    "",
                    "///|",
                    f"pub fn {prefix}_index_set_declaration() -> DeclId {{",
                    f"  make_semantic_id(standard_library_module_id({module['slot']}), {module['index_set']})",
                    "}",
                    "",
                ]
            )
        operation_signature = if_multiline_operation_signature(prefix)
        lines.extend(
            [
                "///|",
                *operation_signature,
                f"  if semantic_id_module(declaration) != standard_library_module_id({module['slot']}) {{",
                "    return NoStandardBuiltinOperation",
                "  }",
                "  match semantic_id_local(declaration) {",
            ]
        )
        for operation, ordinals in module["operations"].items():
            joined = " | ".join(str(value) for value in ordinals)
            lines.append(f"    {joined} => {operation}")
        lines.extend(
            [
                "    _ => NoStandardBuiltinOperation",
                "  }",
                "}",
                "",
            ]
        )

    wasm_intrinsics = modules["wasm_intrinsics"]
    lines.extend(
        [
            "///|",
            "pub fn standard_nullable_ref_type_declaration() -> DeclId {",
            f"  make_semantic_id(standard_library_module_id({wasm_intrinsics['slot']}), {wasm_intrinsics['nullable_ref_type']})",
            "}",
            "",
            "///|",
            *if_multiline_operation_signature("standard_wasm_intrinsics"),
            f"  if semantic_id_module(declaration) != standard_library_module_id({wasm_intrinsics['slot']}) {{",
            "    return NoStandardBuiltinOperation",
            "  }",
            "  match semantic_id_local(declaration) {",
        ]
    )
    for operation, ordinals in wasm_intrinsics["operations"].items():
        joined = " | ".join(str(value) for value in ordinals)
        lines.append(f"    {joined} => {operation}")
    lines.extend(
        [
            "    _ => NoStandardBuiltinOperation",
            "  }",
            "}",
            "",
        ]
    )

    option = modules["option"]
    lines.extend(
        [
            "///|",
            "fn standard_option_type_declaration() -> DeclId {",
            f"  make_semantic_id(standard_library_module_id({option['slot']}), {option['type']})",
            "}",
            "",
            "///|",
            "pub fn standard_option_none_variant() -> VariantId {",
            f"  make_semantic_id(standard_library_module_id({option['slot']}), {option['variants']['none']})",
            "}",
            "",
            "///|",
            "pub fn standard_option_some_variant() -> VariantId {",
            f"  make_semantic_id(standard_library_module_id({option['slot']}), {option['variants']['some']})",
            "}",
            "",
            "///|",
            "fn standard_lane_module_path(index : Int) -> String {",
            "  match index {",
        ]
    )
    for index, lane in enumerate(data["lanes"]):
        if lane["slot"] != 16 + index:
            raise ValueError("lane slots must be contiguous from 16")
        lines.append(f'    {index} => "{lane["path"]}"')
    lines.extend(
        [
            '    _ => abort("unknown standard lane module slot")',
            "  }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = rendered_source()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != rendered:
            raise SystemExit(
                "src/semantic/standard_builtin_registry.mbt is stale; "
                "run tools/generate_standard_builtin_registry.py"
            )
        print(f"checked {TARGET.relative_to(ROOT)}")
        return
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"generated {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
