#!/usr/bin/env python3
"""Generate checked, immediate-free SIMD opcode contracts for both compilers."""

import argparse
import json
import subprocess
from collections import defaultdict
from pathlib import Path

from wasm_simd_intrinsics import SIMD_INSTRUCTIONS, SIMD_LANE_INSTRUCTIONS, SIMD_MEMORY_INSTRUCTIONS, SIMD_SIGNATURES

ROOT = Path(__file__).resolve().parents[1]


def outputs():
    groups = defaultdict(list)
    for opcode, instruction, inputs, result in SIMD_SIGNATURES:
        groups[inputs, result].append(opcode)
    assert len({row[0] for row in SIMD_SIGNATURES}) == len(SIMD_SIGNATURES)
    native = ["// Generated by tools/generate_simd_intrinsics.py.\n///|\n",
              "fn raw_wasm_simd_signature(name : Bytes) -> RawWasmIntrinsicSignature? {\n  match name {\n"]
    dew = ["// Generated by tools/generate_simd_intrinsics.py.\n",
           "fn self_host_raw_simd_signature(name: Bytes) -> Option<SelfHostRawIntrinsicSignature> {\n"]
    for (inputs, result), opcodes in groups.items():
        native_result = "None" if result == "Unit" else f"Some(Wasm{result}Value)"
        native.append("    " + " | ".join(f'b"{op}"' for op in opcodes) + " =>\n")
        native.append("      Some({ inputs: [" + ", ".join(f"Wasm{item}Value" for item in inputs) +
                      f"], result: {native_result}, }})\n")
        dew.append("  if " + " ||\n    ".join(f'name.equals(b"{op}")' for op in opcodes) + " {\n")
        dew.append("    return Option::Some(SelfHostRawIntrinsicSignature::{\n      inputs: [" +
                   ", ".join(f"SelfHostWasmBodyCarrier::{item}BodyCarrier" for item in inputs) +
                   f"]\n      result: SelfHostWasmBodyCarrier::{result}BodyCarrier\n    }})\n  }}\n")
    native.append("    _ => raw_wasm_shuffle_signature(name)\n  }\n}\n")
    native.append("\n///|\nfn raw_wasm_simd_uses_memory(name : Bytes) -> Bool {\n  match name {\n    ")
    native.append(" | ".join(f'b"{row[0]}"' for row in SIMD_MEMORY_INSTRUCTIONS))
    native.append(" => true\n    _ => false\n  }\n}\n")
    dew.append("  self_host_raw_shuffle_signature(name)\n}\n")
    backend = ["// Generated by tools/generate_simd_intrinsics.py.\n///|\n",
               "fn starshine_v128_builtin_instructions(name : Bytes) -> Array[@lib.Instruction]? {\n"]
    backend.append("  match starshine_simd_shuffle_instruction(name) {\n"
                   "    Some(instruction) => return Some([instruction])\n    None => ()\n  }\n")
    for index, (opcode, instruction, _, _) in enumerate(SIMD_INSTRUCTIONS):
        backend.append(f'{"  if" if index == 0 else "else if"} name == b"{opcode}" {{\n'
                       f"    Some([@lib.Instruction::{instruction}()])\n  }} ")
    for opcode, instruction, _, _, indices in SIMD_LANE_INSTRUCTIONS:
        arguments = ", ".join(f"@lib.LaneIdx::new(b'\\x{index:02X}')" for index in indices)
        backend.append(f'else if name == b"{opcode}" {{\n'
                       f"    Some([@lib.Instruction::{instruction}({arguments})])\n  }} ")
    for opcode, instruction, _, _, align, lane in SIMD_MEMORY_INSTRUCTIONS:
        arguments = f"starshine_memory_argument({align}U)"
        if lane is not None:
            arguments += f", @lib.LaneIdx::new(b'\\x{lane:02X}')"
        backend.append(f'else if name == b"{opcode}" {{\n'
                       f"    Some([@lib.Instruction::{instruction}({arguments})])\n  }} ")
    backend.append("else {\n    None\n  }\n}\n")
    cases = ["// Generated by tools/generate_simd_intrinsics.py.\n///|\n",
             "fn raw_simd_test_cases() -> Array[(String, Array[String], String)] {\n  [\n"]
    for opcode, _, inputs, result in SIMD_SIGNATURES:
        cases.append(f'    ("{opcode}", [' + ", ".join(f'"{item}"' for item in inputs) + f'], "{result}"),\n')
    cases.append("  ]\n}\n")
    memory_prelude = (
        'builtin simd_read_vector(address: U32) -> V128 = "v128.load"\n'
        'builtin simd_write_vector(address: U32, value: V128) -> Unit = "v128.store"\n'
    )
    memory_source = ["// Generated by tools/generate_simd_intrinsics.py.\n", memory_prelude]
    memory_fixtures = []
    for index, (opcode, _, _, result, _, lane) in enumerate(SIMD_MEMORY_INSTRUCTIONS):
        parameters = "address: U32" + (", value: V128" if lane is not None else "")
        arguments = "address" + (", simd_read_vector(buffer)" if lane is not None else "")
        declaration = f'builtin memory_operation_{index}({parameters}) -> {result} = "{opcode}"\n'
        call = f"memory_operation_{index}({arguments})"
        if result != "Unit":
            call = f"simd_write_vector(buffer, {call})"
        body = f"pub fn main(address: U32, buffer: U32) -> Unit {{\n  {call}\n}}\n"
        memory_fixtures.append({"opcode": opcode, "source": memory_prelude + declaration + body})
        memory_source.append(declaration + body.replace("fn main(", f"fn probe_{index}("))
    return {
        "src/semantic/raw_wasm_simd_intrinsics.mbt": "".join(native),
        "self_host/compiler/semantic_raw_simd_intrinsics.dew": "".join(dew),
        "src/backend/starshine_v128_builtins.mbt": "".join(backend),
        "src/backend/starshine_raw_simd_cases_wbtest.mbt": "".join(cases),
        "tools/dew-test/simd-opcodes.json": json.dumps(
            [[opcode, inputs, result] for opcode, _, inputs, result in SIMD_SIGNATURES], indent=2
        ) + "\n",
        "tools/dew-test/simd-memory-operations.dew": "".join(memory_source),
        "tools/dew-test/simd-memory-opcodes.json": json.dumps(memory_fixtures, indent=2) + "\n",
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for relative, source in outputs().items():
        path = ROOT / relative
        if path.suffix == ".mbt":
            source = subprocess.run(
                ["moonfmt", "-"], input=source, text=True, capture_output=True, check=True
            ).stdout
        if args.check:
            if not path.exists() or path.read_text() != source:
                raise SystemExit(f"stale generated SIMD source: {relative}")
        else:
            path.write_text(source)


if __name__ == "__main__":
    main()
