#!/usr/bin/env python3
"""Generate package identity tables; these are not physical ABI adapters."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = json.loads((ROOT / "tools/standard-module-identities.json").read_text())
    assert data["version"] == 1, "unsupported identity registry version"
    modules = data["modules"]
    assert len(set(modules.values())) == len(modules), "duplicate module slot"
    assert all(name.startswith("dew.std.") and 0 <= slot < 256 for name, slot in modules.items())
    dew = ["// Generated by tools/generate_standard_module_identities.py.\n",
           "// Return the native semantic identity, not a physical type or function.\n",
           "fn self_host_standard_module_id(path: String) -> U64 {\n"]
    moon = ["///|\n", "// Generated by tools/generate_standard_module_identities.py.\n",
            "fn canonical_standard_module_id(path : String) -> ModuleId? {\n", "  match path {\n"]
    for name, slot in modules.items():
        ident = 0xFFFF0000 + slot
        dew.append(f'  if self_host_manifest_string_equal(path, "{name}") {{\n    return {ident}u64\n  }}\n')
        moon.append(f'    "{name}" => Some({ident}UL)\n')
    dew.append("  0u64\n}\n")
    moon.append("    _ => None\n  }\n}\n")
    for target, contents in [
        ("self_host/compiler/semantic_standard_module_ids.dew", "".join(dew)),
        ("src/semantic/standard_module_identity.mbt", "".join(moon)),
    ]:
        path = ROOT / target
        if args.check:
            if not path.exists() or path.read_text() != contents:
                raise SystemExit(f"{target} is stale; run tools/generate_standard_module_identities.py")
        else:
            path.write_text(contents)
            print(f"generated {target}")


if __name__ == "__main__":
    main()
