#!/usr/bin/env python3
"""Generate direct MoonBit-style tests for scalar conversions and memory APIs."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONVERSIONS = ROOT / "std/tests/generated_conversion_test.dew"
MEMORY = ROOT / "std/tests/generated_memory_test.dew"
LANES = ROOT / "std/tests/generated_lane_smoke_test.dew"

SCALARS = {
    "I8": "42i8", "I16": "42i16", "I32": "42i32", "I64": "42i64",
    "U8": "42u8", "U16": "42u16", "U32": "42u32", "U64": "42u64",
    "F32": "42.0f32", "F64": "42.0f64",
}


def conversion_source() -> str:
    out = ["// Generated by tools/generate_std_tests.py.\n\n"]
    for source, source_value in SCALARS.items():
        for target, target_value in SCALARS.items():
            stem = f"generated_{source.lower()}_to_{target.lower()}"
            out.append(
                f"fn {stem}(value: {source}) -> {target} {{\n"
                "  value.into()\n"
                "}\n\n"
                f"test \"Into {source} to {target}\" {{\n"
                f"  assert({stem}({source_value}) == {target_value}, "
                f"\"Into {source} to {target} failed\")\n"
                "}\n\n"
            )
    return "".join(out)


def memory_source() -> str:
    rows = [
        ("i8", "I8", "-42i8"), ("i16", "I16", "-4242i16"),
        ("i32", "I32", "-424242i32"), ("i64", "I64", "-42424242i64"),
        ("u8", "U8", "213u8"), ("u16", "U16", "4242u16"),
        ("u32", "U32", "424242u32"), ("u64", "U64", "42424242u64"),
        ("f32", "F32", "42.5f32"), ("f64", "F64", "42.5f64"),
    ]
    out = ["// Generated by tools/generate_std_tests.py.\n\n"]
    for index, (stem, type_, value) in enumerate(rows):
        address = index * 16 + 1  # Deliberately unaligned for every width.
        out.append(
            f"test \"{type_} unaligned memory roundtrip\" {{\n"
            f"  {stem}_store({address}u32, {value})\n"
            f"  assert({stem}_load({address}u32) == {value}, "
            f"\"{type_} memory roundtrip failed\")\n"
            "}\n\n"
        )
    out.append(
        "test \"Swar32 unaligned memory roundtrip\" {\n"
        "  let value = swar32_from_bits(305419896u32)\n"
        "  swar32_store(177u32, value)\n"
        "  assert(swar32_to_bits(swar32_load(177u32)) == 305419896u32, "
        "\"Swar32 memory roundtrip failed\")\n"
        "}\n\n"
        "test \"Swar64 unaligned memory roundtrip\" {\n"
        "  let value = swar64_from_bits(81985529216486895u64)\n"
        "  swar64_store(193u32, value)\n"
        "  assert(swar64_to_bits(swar64_load(193u32)) == 81985529216486895u64, "
        "\"Swar64 memory roundtrip failed\")\n"
        "}\n\n"
        "test \"V128 unaligned memory roundtrip\" {\n"
        "  let value = v128_splat_i32(42i32)\n"
        "  v128_store(209u32, value)\n"
        "  assert(!v128_any_true(v128_xor(v128_load(209u32), value)), "
        "\"V128 memory roundtrip failed\")\n"
        "}\n"
    )
    return "".join(out)


def lane_source() -> str:
    lanes = [
        ("i8x4", "I8", "7i8", "9i8", "14i8"),
        ("u8x4", "U8", "7u8", "9u8", "14u8"),
        ("i16x2", "I16", "7i16", "9i16", "14i16"),
        ("u16x2", "U16", "7u16", "9u16", "14u16"),
        ("i8x8", "I8", "7i8", "9i8", "14i8"),
        ("u8x8", "U8", "7u8", "9u8", "14u8"),
        ("i16x4", "I16", "7i16", "9i16", "14i16"),
        ("u16x4", "U16", "7u16", "9u16", "14u16"),
        ("i32x2", "I32", "7i32", "9i32", "14i32"),
        ("u32x2", "U32", "7u32", "9u32", "14u32"),
        ("i8x16", "I8", "7i8", "9i8", "14i8"),
        ("u8x16", "U8", "7u8", "9u8", "14u8"),
        ("i16x8", "I16", "7i16", "9i16", "14i16"),
        ("u16x8", "U16", "7u16", "9u16", "14u16"),
        ("i32x4", "I32", "7i32", "9i32", "14i32"),
        ("u32x4", "U32", "7u32", "9u32", "14u32"),
        ("i64x2", "I64", "7i64", "9i64", "14i64"),
        ("u64x2", "U64", "7u64", "9u64", "14u64"),
        ("f32x4", "F32", "7.0f32", "9.0f32", "14.0f32"),
        ("f64x2", "F64", "7.0f64", "9.0f64", "14.0f64"),
    ]
    out = ["// Generated by tools/generate_std_tests.py.\n"]
    for lane, _, value, replacement, doubled in lanes:
        out.append(f"open dew.std.{lane}\n")
    out.append("\n")
    scalar_packed = {lane for lane, *_ in lanes[:10]}
    for lane, _, value, replacement, doubled in lanes:
        if lane in scalar_packed:
            extract = "extract(0u8)"
            replaced = f"replace(0u8, {replacement}).extract(0u8)"
            added = "add(value).extract(0u8)"
        else:
            extract = "extract_0()"
            replaced = f"replace_0({replacement}).extract_0()"
            added = "add(value).extract_0()"
        out.append(
            f"test \"{lane} splat extract replace and add\" {{\n"
            f"  let value = {lane}_splat({value})\n"
            f"  assert(value.{extract} == {value}, \"{lane} extract failed\")\n"
            f"  assert(value.{replaced} == {replacement}, "
            f"\"{lane} replace failed\")\n"
            f"  assert(value.{added} == {doubled}, "
            f"\"{lane} add failed\")\n"
            "}\n\n"
        )
    return "".join(out)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = {
        CONVERSIONS: conversion_source().rstrip() + "\n",
        MEMORY: memory_source().rstrip() + "\n",
        LANES: lane_source().rstrip() + "\n",
    }
    if args.check:
        stale = [path for path, text in outputs.items() if not path.exists() or path.read_text() != text]
        if stale:
            raise SystemExit("stale generated std tests: " + ", ".join(str(p.relative_to(ROOT)) for p in stale))
        print("checked generated scalar std tests")
        return
    for path, text in outputs.items():
        path.write_text(text)
        print(f"generated {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
